# Generated by Django 5.1.3 on 2024-11-05 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_servicerequest_amount_alter_client_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceprovider',
            name='documentation',
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='provider_type',
            field=models.CharField(choices=[('individual', 'Individual'), ('entity', 'Entity')], default='individual', max_length=20),
        ),
        migrations.CreateModel(
            name='ProviderDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='provider_docs/')),
                ('document_type', models.CharField(max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='dashboard.serviceprovider')),
            ],
        ),
    ]
